name: tmp

on: 
  push:
    branches:
      gh-pages
  workflow_dispatch:

jobs:
  build:    
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install webp
        run: apt install webp
