name: test-webp

on: [workflow_dispatch,push]

jobs:
  build:    
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: intall webp
        run: sudo apt install webp
      - name: change dir
        run: cd src/assets/img/lang/en
      - name: optimize
        run: cwebp -q 60 iphone.png -o iphone.webp
      - name: optimize
        run: ls -la

