name: test-webp

on: [workflow_dispatch,push]

jobs:
  build:    
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: intall webp
        run: sudo apt update && sudo apt install webp
      - name: optimize
        run: cd src/assets/img/lang/en && pwd && cwebp -q 60 iphone.png -o iphone.webp
      - name: show files
        run: ls -la src/assets/img/lang/en

