name: test

on: [workflow_dispatch, push]

jobs:
  tests:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}
    
    env:
      extensions: fileinfo, pdo, pdo_sqlite, intl
      YII_C3: true
    
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04

        php:
          - 8.1
          - 8.2
          
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          tools: composer:v2
          
      - name: Update composer
        run: composer self-update

      - name: Install dependencies with composer
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run tests codeception
        run: ls -la vendor/bin
        
      - name: download bench
        run: wget https://raw.githubusercontent.com/rusoft/php-simple-benchmark-script/master/bench.php
        
      - name: download bench2
        run: wget https://raw.githubusercontent.com/rusoft/php-simple-benchmark-script/master/common.inc
        
        
      - name: size
        run: du -sh * | sort -hr
        
      - name: run bench
        run: php -d max_execution_time=900 bench.php
