name: test-webp

on: 
  push:
    branches:
      test
  workflow_dispatch:

jobs:
  build:    
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: intall webp
        run: apt install webp
