name: test-webp

on: [workflow_dispatch,push]

jobs:
  build:    
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: intall webp
        run: sudo apt update && sudo apt install webp
      - name: change dir
        run: cd src/assets/img/lang/en && pwd
      - name: show files
        run: ls -la
      - name: show version
        run: cwebp -V
      - name: optimize
        run: cwebp iphone.png -o iphone.webp
      - name: show files
        run: ls -la

